version: '3.7'

services:
  django:
    container_name: django
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/src
    ports:
      - "8100:8100"

